services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    # Using the latest Grafana (top of the main branch)
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-main}
    volumes:
      - ./custom.ini:/etc/grafana/grafana.ini
    
