name: Plugins - CD
run-name: Deploy ${{ inputs.branch }} to ${{ inputs.environment }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to publish from. Can be used to deploy PRs to dev
        default: main
      environment:
        description: Environment to publish to
        required: true
        type: choice
        options:
          - 'dev'
          - 'ops'
          - 'prod'
      docs-only:
        description: Only publish docs, do not publish the plugin
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  cd:
    name: CD
    uses: grafana/plugin-ci-workflows/.github/workflows/cd.yml@bdb7870609eebc6d4795493affc2aa35bcbec829
    with:
      branch: ${{ github.event.inputs.branch }}
      environment: ${{ github.event.inputs.environment }}
      docs-only: ${{ fromJSON(github.event.inputs.docs-only) }}
      # Disable playwright tests for now
      run-playwright: false
      grafana-cloud-deployment-type: provisioned
