name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: none
  id-token: none

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@5cb5c6ba12f92e074b5d064847ad9f14f94cc866
    permissions:
      contents: read
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: true
      upload-playwright-artifacts: true
