name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@bdb7870609eebc6d4795493affc2aa35bcbec829
    permissions:
      id-token: none
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: true
      upload-playwright-artifacts: true
