name: Plugins - CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    uses: grafana/plugin-ci-workflows/.github/workflows/ci.yml@ci-cd-workflows/v1.1.2
    permissions:
      contents: read
      id-token: write
    with:
      plugin-version-suffix: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}
      run-playwright: true
      upload-playwright-artifacts: true
      node-version: 22
